### ISSUE TITLE
Naming convention for image tags needed

### ISSUE THREAD

**Issue by jtgasper3** [Unicon/shibboleth-idp-dockerized#1]
We need to tag images as new builds/versions are rev'd. I see high level version tags being there, but we probably need to rev the image on Java and Jetty updates, which will require a more granular tag scheme.

My initial thought is that a scheme should include not only the IdP version, but Java and Jetty as well. Something like `<idp_version>-<java_version>-<jetty_version>-<datestamp>`

Example: `3.1.2-8u60-9.3.3-20150810`

Or what about using the idp version with a datestamp like <idp_version>-<datestamp>

Example: `3.1.2-20150802`

The former makes it very clear the embedded Java and Jetty version. The latter will require a crosswalk table to track versions, but is a bit more manageable.

**Comment by andrewstuart** [comment]
Additionally, a lot of the more popular repos have shorthand tags that mean semantically "latest in the subset of <tag>". For example, [golang](https://hub.docker.com/_/golang/), [node](https://hub.docker.com/_/node/), and [php](https://hub.docker.com/_/php/).

So, you could set up shibboleth-idp:3 to always point to whatever the latest build of version 3 is. Likewise, :3.2 would point to the latest patch release of 3.2.*.

That way, anybody can tag the exact version if they have strict requirements, but they can also "subscribe" to updates by allowing one of the more-flexible tags (but still stricter than :latest).

**Comment by ozbillwang** [comment]
I vote for naming as `3.1.2-20150802`, for java/jetty version, I am not really care of it.

**Comment by jtgasper3** [comment]
Thanks SydOps. I've been using that scheme sucessfully with another project. I'll document somewhere the various versions associated with the tag (or one can check the git repo tag)

**Comment by jtgasper3** [comment]
Thanks for everyone's feedback. I'm going forward with the <Idpversion>-<build date> (e.g 3.1.2-20150802).
