### ISSUE TITLE
Need to add instructions on adding JCE Unlimited Strength Jurisdiction Policy Files

### ISSUE THREAD

**Issue by jtgasper3** [Unicon/shibboleth-idp-dockerized#2]
We don't want to ship the Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files due to export restrictions/licensing. We should provide instructions to ease users of the image to overlay the jars.

See http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

**Comment by mmoayyed** [comment]
I'd say ship them, but put a warning on the GitHub repo's readme.

**Comment by jtgasper3** [comment]
I don't know that they can be included unless we enforce the export restrictions ourselves. I don't think we can do that. 

I'll be reading through the licensing agreement to see if I can get a better idea of the specifics, but I think we can certainly provide the Dockerfile that can be used to import them, or just an explanation of where to download and place them in their own overlay.

**Comment by mmoayyed** [comment]
Sounds good. I'd just add that since you'd be providing the config on Github, Github itself is protected via export restrictions and will stop access. So the enforcement happens at that level for you already :) 

P.S: Of course, this is just formality and precautions. Any proxy would do the job :)

**Comment by jtgasper3** [comment]
That's a good note about GH providing restrictions... Do you know if Docker Hub provides the same functionality? If this becomes official and is signed, then that would be the place I'd expect most to download this base image. More to research... :)
