### ISSUE TITLE
Look into Automated Builds and Webhooks

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/shibboleth-idp-dockerized#3]
https://docs.docker.com/docker-hub/builds/

**Comment by jtgasper3** [comment]
LOL, what? This will be an automated build once it is stable... I've got a few more tweaks and some testing before I do that push and enable that like the other builds have.

**Comment by mmoayyed** [comment]
So, you mean, once you are ready with the changes here if I push a change to this repo I will automatically have the image built on docker hub? If so, wunderbar!

**Comment by jtgasper3** [comment]
Yes... for those with committer status... haven't decided if you should be on the list or not. Totally, joking... mostly. :D

**Comment by mmoayyed** [comment]
:) Kewl. 
- Misagh
