### ISSUE TITLE
init-idp.sh hangs

### ISSUE THREAD

**Issue by tomwganem** [Unicon/shibboleth-idp-dockerized#30]
I tried following the instructions in the README to generate my initial IdP configuration and it just hangs.

```
tganem@bentley:~/Development$ docker run -it -v $(pwd):/ext-mount --rm unicon/shibboleth-idp init-idp.sh
Hostname: [4531ebe2869e.localdomain]
```

**Comment by mmoayyed** [comment]
What version of docker? I have run into this issue before. Restarting docker or tbe docker machine usually clears things up. Have u tried that?

**Comment by tomwganem** [comment]
docker version 1.12.3
restarting docker doesn't fix it

```
tganem@bentley:~/Development/dockerized-idp-testbed$ docker -v
Docker version 1.12.3, build 6b644ec
tganem@bentley:~/Development/dockerized-idp-testbed$ sudo service docker restart
tganem@bentley:~/Development/dockerized-idp-testbed$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
tganem@bentley:~/Development/dockerized-idp-testbed$ docker run -it -v $(pwd):/ext-mount --rm unicon/shibboleth-idp init-idp.sh
Hostname: [1b8f657a253a.localdomain]
```

**Comment by tomwganem** [comment]
It should also be noted that not mounting the /ext-mount directory does not fix the issue.

**Comment by jtgasper3** [comment]
Are you trying to type in a new host name? Or pressing **Enter** to accept the default?

**Comment by tomwganem** [comment]
Ah geez. No. I didn't realize that it was a prompt.

**Comment by jtgasper3** [comment]
Totally understand. In fact, let's convert this to an issue and I'll add a prompt.

**Comment by tomwganem** [comment]
Thank you.

**Comment by jtgasper3** [comment]
Commit fc65a7ea44e9b00048bc630c97b0f82075bf948b

Building now.
