### ISSUE TITLE
Cannot create directory in container?

### ISSUE THREAD

**Issue by cragr** [Unicon/shibboleth-idp-dockerized#33]
When running this command `docker run -it -v $(pwd):/ext-mount --rm unicon/shibboleth-idp init-idp.sh`

I get the following error message:

```
BUILD SUCCESSFUL
Total time: 11 seconds
mkdir: cannot create directory '/ext-mount/customized-shibboleth-idp': Permission denied
cp: cannot create directory '/ext-mount/customized-shibboleth-idp/': Permission denied
cp: cannot create directory '/ext-mount/customized-shibboleth-idp/': Permission denied
cp: target '/ext-mount/customized-shibboleth-idp/conf/' is not a directory
cp: cannot create directory '/ext-mount/customized-shibboleth-idp/': Permission denied
mkdir: cannot create directory '/ext-mount/customized-shibboleth-idp/webapp/': No such file or directory
cp: cannot create directory '/ext-mount/customized-shibboleth-idp/webapp/': No such file or directory
cp: cannot create directory '/ext-mount/customized-shibboleth-idp/webapp/': No such file or directory
cp: cannot create directory '/ext-mount/customized-shibboleth-idp/webapp/': No such file or directory
rm: cannot remove '/ext-mount/customized-shibboleth-idp/views/user-prefs.js': No such file or directory
A basic Shibboleth IdP config and UI has been copied to ./customized-shibboleth-idp/ (assuming the default volume mapping was used).
Most files, if not being customied can be removed from what was exported/the local Docker image and baseline files will be used.
```

**Comment by jtgasper3** [comment]
So I do get an error with a 3.3.0 based image:

```
BUILD SUCCESSFUL
Total time: 11 seconds
rm: cannot remove '/ext-mount/customized-shibboleth-idp/views/user-prefs.js': Permission denied
A basic Shibboleth IdP config and UI has been copied to ./customized-shibboleth-idp/ (assuming the default volume mapping was used).
Most files, if not being customied can be removed from what was exported/the local Docker image and baseline files will be used.
```

Can you please tell me about your environment? Are you running Docker on Linux directly or using an OS X or Windows abstraction? Also do you have privs to create directories, etc in you present working directory (pwd)?

**Comment by cragr** [comment]
I am using docker directly on RHEL 7.3.  As far as permissions I sudo up to run the docker command but have also tried created an idp folder in my home directory and doing a "-v /home/me/idp:/ext-mount".  Oddly if I run the image and /bin/bash in I can run the init-idp.sh successfully from inside the image.

**Comment by jtgasper3** [comment]
>  am using docker directly on RHEL 7.3.

That'll take me a bit to be able to setup a VM to replicate that setup. What docker engine version are you on?

> Oddly if I run the image and /bin/bash in I can run the init-idp.sh successfully from inside the image.

That is curious. And it creates the keys and config files on the host machine as expected?

**Comment by cragr** [comment]
> That'll take me a bit to be able to setup a VM to replicate that setup. What docker engine version are you on?

I tried just now on a CentOS 7 VM with the same result.  Both VM's are using docker 1.10.3.  I'll try a different docker version.

> That is curious. And it creates the keys and config files on the host machine as expected?

It only creates the files in the image, I could just copy them over.

**Comment by cragr** [comment]
Newer version of docker from the docker repo works great.  The docker from the @extras repo apparently does not.  Thanks for the help.

**Comment by mmoayyed** [comment]
As a general rule, I have often found OS distros and repos to be problematic. Getting packages from the project's directly always has solved a lot of weird issues and is likely a more secure approach.

**Comment by cragr** [comment]
Just trying to keep it RHEL. lol

**Comment by jtgasper3** [comment]
> Newer version of docker from the docker repo works great. The docker from the @extras repo apparently does not. Thanks for the help.

Yeah 1.10.3 is pretty old (relatively speaking) as I'd guess you are probably at 1.12.X now. There's been significant improvement in that gap.
