### ISSUE TITLE
Master and 3.3.0 image use idp 3.2.1

### ISSUE THREAD

**Issue by cata86** [Unicon/shibboleth-idp-dockerized#35]
master and 3.3.0 tag not use the idp shibboleth 3.3.0 version.

**Comment by jtgasper3** [comment]
Hi cata86,

Can you please share some details on that assessment?

I did just notice that https://github.com/Unicon/shibboleth-idp-dockerized/blob/master/Dockerfile#L7 references 3.2.1 but that is just a label and not the contents of the image...  After running:

```
docker pull unicon/shibboleth-idp:3.3.0
3.3.0: Pulling from unicon/shibboleth-idp
Digest: sha256:2225da3cb1dab94db61290243d86cfc6fa374c796f8c8524e29721509c0a135f
Status: Image is up to date for unicon/shibboleth-idp:3.3.0
```

the libs in `/opt/shibboleth-idp/webapp/WEB-INF/lib` reference 3.3.0:

```
idp-admin-api-3.3.0.jar
idp-admin-impl-3.3.0.jar
idp-attribute-api-3.3.0.jar
idp-attribute-filter-api-3.3.0.jar
idp-attribute-filter-impl-3.3.0.jar
idp-attribute-filter-spring-3.3.0.jar
idp-attribute-resolver-api-3.3.0.jar
idp-attribute-resolver-impl-3.3.0.jar
idp-attribute-resolver-spring-3.3.0.jar
idp-authn-api-3.3.0.jar
idp-authn-impl-3.3.0.jar
idp-cas-api-3.3.0.jar
idp-cas-impl-3.3.0.jar
idp-consent-api-3.3.0.jar
idp-consent-impl-3.3.0.jar
idp-core-3.3.0.jar
idp-profile-api-3.3.0.jar
idp-profile-impl-3.3.0.jar
idp-profile-spring-3.3.0.jar
idp-saml-api-3.3.0.jar
idp-saml-impl-3.3.0.jar
idp-schema-3.3.0.jar
idp-session-api-3.3.0.jar
idp-session-impl-3.3.0.jar
```

Thanks,
John

**Comment by jtgasper3** [comment]
The label has been fixed and the images are rebuilding, but please do share info on where the content appear to be Idp 3.2.1, if you weren't just referring to the label.

**Comment by cata86** [comment]
you are right.
it's just the label.
