### ISSUE TITLE
Bad file modes in customized shibboleth configuration

### ISSUE THREAD

**Issue by jsandas** [Unicon/shibboleth-idp-dockerized#37]
When I run the command to generate a customized config:

"docker run -it -v $(pwd):/ext-mount --rm unicon/shibboleth-idp init-idp.sh"

Some of the folders/file it generates have file modes which make them not accessible for me.

Example:
customized-shibboleth-idp/views is set to mode 640 which makes the directory not browsable.  The same thing applies to the contents of this folder as well as customized-shibboleth-idp/credentials and customerized-shibboleth-idp/webapp folders.

Was this expected behavior?

Thanks

**Comment by sesm** [comment]
I'm having the same issue with file modes.
(running on macOS 10.12)

**Comment by jtgasper3** [comment]
Hey @sesm  and @jsandas,

Sorry, I missed this ticket. Were you able to retrieve the files by changing the permissions on the directory?

This is not expected behavior. The script probably just needs to change the privs before it finishes.

**Comment by charyorde** [comment]
```
chmod -R 755 customized-shibboleth-idp/views
chmod -R 755 customized-shibboleth-idp/credentials
chmod -R 755 customized-shibboleth-idp/webapp
```
A quick resolution for me.

**Comment by jtgasper3** [comment]
I think this has been resolved... a while ago. Thanks for the info.
