### ISSUE TITLE
idp-browser.p12 not generated by `init-idp.sh`

### ISSUE THREAD

**Issue by sesm** [Unicon/shibboleth-idp-dockerized#38]
According to documentation on https://hub.docker.com/r/unicon/shibboleth-idp/, the steps for running container are the following:
1. Generate configuration by running 
```shell
docker run -it -v $(pwd):/ext-mount --rm unicon/shibboleth-idp init-idp.sh
```
2. Create Dockerfile and build customized image with
```shell
docker build --tag="<org_id>/shibboleth-idp:<version>" .
```
3. Run the customized image with
```shell
docker run -e<passwords go here> <org_id>/shibboleth-idp
```
 
However, step 3 failed for me with
```
java.lang.IllegalStateException: no valid keystore
```
The reason for this is that at step 1 file 'credentials/idp-browser.p12' was not generated. 
When I generated this file and manually put it to 'credentials' folder before step 2, docker image started successfully.
I suppose 'idp-browser.p12' should have been generated when running 'init-idp.sh', but silently failed for some reason.

My environment: macOS 10.12, docker 1.13.1
The issue is 100% reproducible, if you need any logs/command outputs please ping me.

**Comment by jtgasper3** [comment]
Hi @sesm,

Please keep reading down to https://github.com/Unicon/shibboleth-idp-dockerized#browser-based-tls-certificate-and-key

The cert needed here is not one that the IdP install creates for you. You should generate your own key and CSR and combine the key and signed cert (and root/intermediate certs) into a p12 file. This set is used for browser based TLS connections. If you need one for testing, see https://github.com/UniconLabs/dockerized-idp-testbed/tree/master/idp/shibboleth-idp/credentials.

**Comment by sesm** [comment]
@jtgasper3 thank you for clarification!
