### ISSUE TITLE
How to tweak loglevels ?

### ISSUE THREAD

**Issue by lrhazi** [Unicon/shibboleth-idp-dockerized#42]
I tried adding lines like so to conf/idp.properties

```
idp.loglevel.idp=DEBUG
idp.loglevel.ldap=INFO
idp.loglevel.opensaml=DEBUG
```

But they dont seem to take effect on image rebuild.
What is the correct or easiest way to do this?

Thanks a lot
Mohamed.

**Comment by jtgasper3** [comment]
The `logback.xml` is the one physical file that replaces the baseline file. This is to log to the `console` to support Docker logging.

I have apparently missed diff'ing this file, and it is old and doesn't have the variable support it should. I'll get this changed by the end of the day. `3.3.1` and `3.2.1` will be updated with the fix.

**Comment by jtgasper3** [comment]
`3.3.1` has been updated (and I updated `3.3.1-20170315`) as well. 3.2.1 is next.

**Comment by jtgasper3** [comment]
`3.2.1` has been updated, and `3.2.1-20170315` has been published. 

@lrhazi, Can you please do a `docker pull unicon/shibboleth-idp:<tag>`, and let me know if that fixes things for you? Thanks.

**Comment by lrhazi** [comment]
Seems to work! Thanks a lot.
