### ISSUE TITLE
Docker container hosting Shibboleth IdP crashes within 8 hours on hosted Docker container

### ISSUE THREAD

**Issue by winstonhong** [Unicon/shibboleth-idp-dockerized#45]
(1) Run Docker container for Shibboleth IdP directly on Ubuntu16.04/VMWare

Run the 2nd separate Docker container for OpenLDAP on the same Ubuntu16.04/VMWare

Run the 3rd separate Docker container for MySQL on the same Ubuntu16.04/VMWare

Execute the command 
docker run -p 8443:8443 --name idp1 --link ldap:ldap --link mysql:mysql idq/shibboleth-idp:001

Experimental result:
Docker container hosting Shibboleth IdP runs reliably on Ubuntu16.04/VMWare for more than 1 week

(2) Run Docker container for Shibboleth IdP on Ubuntu16.04/Docker container

Run the 2nd separate Docker container for OpenLDAP on the same Ubuntu16.04/Docker container
https://github.com/UniconLabs/dockerized-idp-testbed/tree/master/ldap

Run the 3rd separate Docker container for MySQL on the same Ubuntu16.04/Docker container

Execute the command 
docker run -p 8443:8443 --name idp1 --link ldap:ldap --link mysql:mysql idq/shibboleth-idp:001

Experimental result:
Docker container hosting Shibboleth IdP crashes on Ubuntu16.04/Docker container within 8 hours. However, both the Docker container hosting OpenLDAP and the Docker container hosting MySQL run reliably on the same Ubuntu16.04/Docker container.

We have to re-execute the command to start the Docker container hosting Shibboleth IdP again

8443: 8443 host:container 

Remarks:

(I) We use HAProxy to proxy internal port 8443 of Shibboleth IdP host to external port 443. 
For example, IP address/Port of internal Shibboleth IdP host is 192.168.150.100:8443
is proxies to 
IP address/Port of external Shibboleth IdP host is 134.129.102.100:443

(II) Once we re-start HAProxy, Docker container hosting Shibboleth IdP crashes immediately. However, other Docker containers which also rely on the same HAProxy run reliably.

https://en.wikipedia.org/wiki/HAProxy

https://github.com/UniconLabs/dockerized-idp-testbed/tree/master/httpd-proxy

**Comment by jtgasper3** [comment]
@winstonhong,

Were you ever able to get to the bottom of this? I know folks using this that haven't had the same issue.

Thanks,
John

P.S. Sorry for the long delay in responding.

**Comment by winstonhong** [comment]
Thank you very much for your feedback comments.

Our deployment team has fixed the issue of HAProxy with Dockerized Shibboleth IdP. 

Now Docker container hosting Shibboleth IdP continues to run reliably after we re-start HAProxy.
