### ISSUE TITLE
Does this implement "Secret Key Management" rollover

### ISSUE THREAD

**Issue by markvr** [Unicon/shibboleth-idp-dockerized#52]
As described at:  https://wiki.shibboleth.net/confluence/display/IDP30/SecretKeyManagement

If so, how can the daily generated key be distributed between servers running this image?

**Comment by jtgasper3** [comment]
This does not. That is an implementation detail that this image can not readily take care of. Variables such as the orchestration tool (Swarm, Kubernetes, ECS, etc) and backing-files/secrets storage all come into play here. If you supply the sealer.jks as a Docker Secret, then it is mounted read-only and cannot be changed in place.

You can certainly use the idp container to run `seckeygen.sh`. Something like:

```
docker run -it --rm \
  --mount type=bind,src=$(pwd)/secrets/sealer.jks,dst=/opt/shibboleth-idp/credentials/sealer.jks \
  --mount type=bind,src=$(pwd)/secrets/sealer.kver,dst=/opt/shibboleth-idp/credentials/sealer.kver \
unicon/shibboleth-idp:<tag> /opt/shibboleth-idp/bin/seckeygen.sh \
    --storefile /opt/shibboleth-idp/credentials/sealer.jks \
    --storepass password \
    --versionfile /opt/shibboleth-idp/credentials/sealer.kver \
    --alias secret
```

that would update the file on your system, then you update those secrets in your live IdP containers using the standard orchestration tool means.

**Comment by markvr** [comment]
ok great, thanks for the quick response!
