### ISSUE TITLE
Cant run init-idp.sh successfully

### ISSUE THREAD

**Issue by CbxDunderklumpen** [Unicon/shibboleth-idp-dockerized#60]
I'm trying to get started with this, running from docker-machine on windows, and I'm getting stuck running the initial docker run 

`docker run -v ///c/Users/<user>/shibboleth-conf:/ext-mount -it --rm unicon/shibboleth-idp init-idp.sh`

I can see the mount suceeding.
The init-idp.sh starts and I run through the questions.

The last successful messages are:
```
Cookie Encryption Key Password:
Re-enter password:
Creating cookie encryption key files...
...done
```
The I get the messages 

```
BUILD FAILED
/opt/shibboleth-identity-provider-3.4.1/bin/build.xml:505: Non-existent input file

Total time: 43 seconds
cp: cannot stat 'conf/attribute-resolver.xml': No such file or directory
cp: cannot stat 'conf/attribute-filter.xml': No such file or directory
cp: cannot stat 'conf/cas-protocol.xml': No such file or directory
cp: cannot stat 'conf/idp.properties': No such file or directory
cp: cannot stat 'conf/ldap.properties': No such file or directory
cp: cannot stat 'conf/metadata-providers.xml': No such file or directory
cp: cannot stat 'conf/relying-party.xml': No such file or directory
cp: cannot stat 'conf/saml-nameid.xml': No such file or directory
A basic Shibboleth IdP config and UI has been copied to ./customized-shibboleth-idp/ (assuming the default volume mapping was used).
Most files, if not being customized can be removed from what was exported/the local Docker image and baseline files will be used.
```

I can see that a `customized-shibboleth-idp` dir has been created, along with a bunch of sub-dirs (including `conf`), but that's as far as I get

**Comment by jtgasper3** [comment]
I'll have to take a look. As a workaround, I'd just `bash` into the container, run the full install.sh and then copy the needed files over to the mounted directory.

**Comment by immilev** [comment]
Apparently, the init-idp.sh expects to find some files in a dist directory (line 505 in build.xml), but this directory disappeared from the shibboleth-idp-3.4.x-tar.gz tarballs.  A number of ant targets use it, including the editproperties task.  The last image in which the init-idp.sh/install.sh work seems to be 3.3.3.

I could not get the workaround to work. The copy-distribution ant task also breaks.

C:\imilev\git>docker run -it unicon/shibboleth-idp:latest bash
[root@9654a4d32eb5 /]# cd /opt/shibboleth-idp
[root@9654a4d32eb5 shibboleth-idp]# export JAVA_HOME=/opt/jre-home
[root@9654a4d32eb5 shibboleth-idp]# export PATH=$PATH:$JAVA_HOME/bin
[root@9654a4d32eb5 shibboleth-idp]# bin/install.sh
Source (Distribution) Directory (press <enter> to accept default): [/opt/shibboleth-identity-provider-3.4.2]
Installation Directory: [/opt/shibboleth-idp]
Warning: /opt/shibboleth-idp/edit-webapp does not exist.
Warning: /opt/shibboleth-idp/dist does not exist.

BUILD FAILED
/opt/shibboleth-identity-provider-3.4.2/bin/build.xml:642: /opt/shibboleth-identity-provider-3.4.2/doc does not exist.

Total time: 8 seconds
[root@9654a4d32eb5 shibboleth-idp]# cat idp_ant.log
target: init
target: getsource
target: target-properties
target: target-nosrc-default
target: prompttarget
target: v2detect
target: checkproperties
target: copy-distribution
[root@9654a4d32eb5 shibboleth-idp]#

**Comment by jtgasper3** [comment]
Thanks for the additional information. I'll be looking into this today. Let's see what I can figure out.

**Comment by jtgasper3** [comment]
OK, @immilev and @CbxDunderklumpen, I've re-worked the logic and have pushed the changes. The new images are building now. If you were building your own images from source, you can now do that.

Thanks again for the reports and analysis.

**Comment by CbxDunderklumpen** [comment]
Thanks for resolving this @jtgasper3 and for the additional investigation by @immilev. I discovered this bug just before a long break from work, so I'm sorry I couldn't provide more input.  I'm really happy to see it resolved.
