### ISSUE TITLE
Unable to find image '...' locally

### ISSUE THREAD

**Issue by dlq** [Unicon/shibboleth-idp-dockerized#62]
I followed the install instructions but at the very last step I'm getting:

`$ docker run -d --name="shib-local-test" 32625ac827d8.localdomain/shibboleth-idp`
`Unable to find image '32625ac827d8.localdomain/shibboleth-idp:latest' locally`
`docker: Error response from daemon: Get https://32625ac827d8.localdomain/v2/: Service Unavailable.`
`See 'docker run --help'.`

What am I missing?

**Comment by jtgasper3** [comment]
You are trying to pull an image from a registry hosted by `32625ac827d8.localdomain`.  You either need to build the image locally using the same name or remove what Docker is interrupting to be a hostname from the image name.

**Comment by dlq** [comment]
Ugh.  I forgot the version at the end.  The full tag locally is '32625ac827d8.localdomain/shibboleth-idp:3.4.3'.

The container is now running.

**Comment by jtgasper3** [comment]
Oops. That'll do it. Glad it is up an running.
